### ISSUE TITLE
Angular build error 0.14.0+

### ISSUE THREAD

**Issue by ssavchuk-trimble** [trimble-oss/modus-web-components#2140]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When updating `@trimble-oss/modus-angular-components` to 0.16.0-ng15 at `angular-workspace/test-ng15/package.json` and then running `npm i && npm run build` from `angular-workspace/test-ng15` it causes such error:

```
Error: node_modules/@trimble-oss/modus-web-components/dist/types/interfaces.d.ts:21:31 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './icons/ModusIconUtilities.js' instead.

21 export { ModusIconName } from './icons/ModusIconUtilities.ts';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Reduced test cases

See above. Update from `"@trimble-oss/modus-angular-components": "0.11.0-ng15"` to `"@trimble-oss/modus-angular-components": "0.14.0-ng15"` or later causes the error above.

### What operating system(s) are you seeing the problem on?

Windows

### What is the issue regarding ?

@trimble-oss/modus-web-components, @trimble-oss/modus-angular-components

### What version of npm package are you using ?

16.17.0

### Priority

Medium

### What product/project are you using Modus Components for ?

AbsencePlanner

### What is your team/division name ?

AbsencePlanner

### Are you willing to contribute ?

None
